### PR TITLE
Add auto layout helpers for centering a view vertically or horizontally.

### PR DESCRIPTION
**Pull request by spenrose**

### CODE REVIEW

**Comment by spenrose** [comment]
@jnjosh Here is the jams we talked about.

**Comment by jnjosh** [comment]
This looks okay to me. Working on fixing some Travis Stuff then I'll merge.

**Comment by spenrose** [comment]
Yo noobs! Lets get this merged... it isn't rocket science! 

Love aggro scott

**Comment by jnjosh** [comment]
:scissors: Rocket Science :microscope:

**Pull request merged**
